### PR TITLE
Backend tink

### PR DESCRIPTION
**Pull request by jacobweinstock**
## Description

This is a backend implementation for getting DHCP options from Tink server. 
FYI, pulling in the Tink library dependency made the `go.sum` file change by 1,943 lines! :(

## Why is this needed

Fixes: #

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by displague** [comment]
Should this live in internal/backend until the need arises to export `Config`? Is exporting an intended goal?

**Comment by jacobweinstock** [comment]
> Should this live in internal/backend until the need arises to export `Config`? Is exporting an intended goal?

This is an implementation of the [`BackendReader` interface](https://github.com/tinkerbell/dhcp/blob/ac57294ee6f28595c151a02256f62bf0ebdc7148/handler.go#L22) and clients using `Server` struct [here](https://github.com/tinkerbell/dhcp/blob/ac57294ee6f28595c151a02256f62bf0ebdc7148/dhcp.go#L19) will want to be able to specify the tink backend. There's an example in the PR [here](https://github.com/tinkerbell/dhcp/blob/1812dd2026aa96dc53b7718f3bd4e7fc5febf597/example/main.go)

**Comment by displague** [comment]
> > Should this live in internal/backend until the need arises to export Config? Is exporting an intended goal?
>
> This is an implementation of the [BackendReader interface](https://github.com/tinkerbell/dhcp/blob/ac57294ee6f28595c151a02256f62bf0ebdc7148/handler.go#L22) and clients using Server struct [here](https://github.com/tinkerbell/dhcp/blob/ac57294ee6f28595c151a02256f62bf0ebdc7148/dhcp.go#L19) will want to be able to specify the tink backend. T[here](https://github.com/tinkerbell/dhcp/blob/1812dd2026aa96dc53b7718f3bd4e7fc5febf597/example/main.go)'s an example in the PR here


`tink.DHCPBackend`?
`tink.Backend` perhaps?

**Comment by jacobweinstock** [comment]
> > > Should this live in internal/backend until the need arises to export Config? Is exporting an intended goal?
> > 
> > 
> > This is an implementation of the [BackendReader interface](https://github.com/tinkerbell/dhcp/blob/ac57294ee6f28595c151a02256f62bf0ebdc7148/handler.go#L22) and clients using Server struct [here](https://github.com/tinkerbell/dhcp/blob/ac57294ee6f28595c151a02256f62bf0ebdc7148/dhcp.go#L19) will want to be able to specify the tink backend. T[here](https://github.com/tinkerbell/dhcp/blob/1812dd2026aa96dc53b7718f3bd4e7fc5febf597/example/main.go)'s an example in the PR here
> 
> `tink.DHCPBackend`? `tink.Backend` perhaps?

Hey @displague, name changed. Please take a look when you have a moment.

**Comment by jacobweinstock** [comment]
closing for now because of https://github.com/tinkerbell/proposals/pull/58. If that does not go through i will reopen this.

**Pull request closed without merging**
